//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ici.nmfp.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ici.nmfp.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATERANGETYPE }
     * 
     */
    public DATERANGETYPE createDATERANGETYPE() {
        return new DATERANGETYPE();
    }

    /**
     * Create an instance of {@link PERCENTAGEOFTOTALASSETINVESTEDDAILY }
     * 
     */
    public PERCENTAGEOFTOTALASSETINVESTEDDAILY createPERCENTAGEOFTOTALASSETINVESTEDDAILY() {
        return new PERCENTAGEOFTOTALASSETINVESTEDDAILY();
    }

    /**
     * Create an instance of {@link PERCENTAGEOFTOTALASSETINVESTED }
     * 
     */
    public PERCENTAGEOFTOTALASSETINVESTED createPERCENTAGEOFTOTALASSETINVESTED() {
        return new PERCENTAGEOFTOTALASSETINVESTED();
    }

    /**
     * Create an instance of {@link TOTALVALUEOFLIQUIDASSETDAILY }
     * 
     */
    public TOTALVALUEOFLIQUIDASSETDAILY createTOTALVALUEOFLIQUIDASSETDAILY() {
        return new TOTALVALUEOFLIQUIDASSETDAILY();
    }

    /**
     * Create an instance of {@link TOTALVALUEOFLIQUIDASSET }
     * 
     */
    public TOTALVALUEOFLIQUIDASSET createTOTALVALUEOFLIQUIDASSET() {
        return new TOTALVALUEOFLIQUIDASSET();
    }

    /**
     * Create an instance of {@link NETASSETVALUE }
     * 
     */
    public NETASSETVALUE createNETASSETVALUE() {
        return new NETASSETVALUE();
    }

}
