//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for TOTAL_VALUE_OF_LIQUID_ASSET_DAILY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TOTAL_VALUE_OF_LIQUID_ASSET_DAILY"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fridayDay1" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="fridayDay2" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="fridayDay3" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="fridayDay4" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="fridayDay5" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TOTAL_VALUE_OF_LIQUID_ASSET_DAILY", propOrder = {
    "fridayDay1",
    "fridayDay2",
    "fridayDay3",
    "fridayDay4",
    "fridayDay5"
})
public class TOTALVALUEOFLIQUIDASSETDAILY {

    protected BigDecimal fridayDay1;
    protected BigDecimal fridayDay2;
    protected BigDecimal fridayDay3;
    protected BigDecimal fridayDay4;
    protected BigDecimal fridayDay5;

    /**
     * Gets the value of the fridayDay1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFridayDay1() {
        return fridayDay1;
    }

    /**
     * Sets the value of the fridayDay1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFridayDay1(BigDecimal value) {
        this.fridayDay1 = value;
    }

    /**
     * Gets the value of the fridayDay2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFridayDay2() {
        return fridayDay2;
    }

    /**
     * Sets the value of the fridayDay2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFridayDay2(BigDecimal value) {
        this.fridayDay2 = value;
    }

    /**
     * Gets the value of the fridayDay3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFridayDay3() {
        return fridayDay3;
    }

    /**
     * Sets the value of the fridayDay3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFridayDay3(BigDecimal value) {
        this.fridayDay3 = value;
    }

    /**
     * Gets the value of the fridayDay4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFridayDay4() {
        return fridayDay4;
    }

    /**
     * Sets the value of the fridayDay4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFridayDay4(BigDecimal value) {
        this.fridayDay4 = value;
    }

    /**
     * Gets the value of the fridayDay5 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFridayDay5() {
        return fridayDay5;
    }

    /**
     * Sets the value of the fridayDay5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFridayDay5(BigDecimal value) {
        this.fridayDay5 = value;
    }

}
