//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for COLLATERAL_INVESTMENT_CATEGORY_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="COLLATERAL_INVESTMENT_CATEGORY_TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Asset-Backed Securities"/&gt;
 *     &lt;enumeration value="Agency Collateralized Mortgage Obligation"/&gt;
 *     &lt;enumeration value="Agency Debentures and Agency Strips"/&gt;
 *     &lt;enumeration value="Agency Mortgage-Backed Securities"/&gt;
 *     &lt;enumeration value="Private Label Collateralized Mortgage Obligations"/&gt;
 *     &lt;enumeration value="Corporate Debt Securities"/&gt;
 *     &lt;enumeration value="Equities"/&gt;
 *     &lt;enumeration value="Money Market"/&gt;
 *     &lt;enumeration value="U.S. Treasuries (including strips)"/&gt;
 *     &lt;enumeration value="Other Instrument"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "COLLATERAL_INVESTMENT_CATEGORY_TYPE")
@XmlEnum
public enum COLLATERALINVESTMENTCATEGORYTYPE {

    @XmlEnumValue("Asset-Backed Securities")
    ASSET_BACKED_SECURITIES(1, "Asset-Backed Securities"),
    @XmlEnumValue("Agency Collateralized Mortgage Obligation")
    AGENCY_COLLATERALIZED_MORTGAGE_OBLIGATION(2, "Agency Collateralized Mortgage Obligation"),
    @XmlEnumValue("Agency Debentures and Agency Strips")
    AGENCY_DEBENTURES_AND_AGENCY_STRIPS(3, "Agency Debentures and Agency Strips"),
    @XmlEnumValue("Agency Mortgage-Backed Securities")
    AGENCY_MORTGAGE_BACKED_SECURITIES(4, "Agency Mortgage-Backed Securities"),
    @XmlEnumValue("Private Label Collateralized Mortgage Obligations")
    PRIVATE_LABEL_COLLATERALIZED_MORTGAGE_OBLIGATIONS(5, "Private Label Collateralized Mortgage Obligations"),
    @XmlEnumValue("Corporate Debt Securities")
    CORPORATE_DEBT_SECURITIES(6, "Corporate Debt Securities"),
    @XmlEnumValue("Equities")
    EQUITIES(7, "Equities"),
    @XmlEnumValue("Money Market")
    MONEY_MARKET(8, "Money Market"),
    @XmlEnumValue("U.S. Treasuries (including strips)")
    U_S_TREASURIES_INCLUDING_STRIPS(9, "U.S. Treasuries (including strips)"),
    @XmlEnumValue("Other Instrument")
    OTHER_INSTRUMENT(10, "Other Instrument");

    private final int id;
    private final String value;

    COLLATERALINVESTMENTCATEGORYTYPE(int id, String v) {
        this.id = id;
        value = v;
    }

    public Integer id() {
        return id;
    }
    public String value() {
        return value;
    }

    public static COLLATERALINVESTMENTCATEGORYTYPE fromValue(String v) {
        for (COLLATERALINVESTMENTCATEGORYTYPE c: COLLATERALINVESTMENTCATEGORYTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
