//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import org.ici.nmfp2.edgar_common.LIVETESTTYPE;
import org.ici.nmfp2.edgar_common.YESNOTYPE;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * These elements are part of the FILER_INFO_TYPE group
 * 
 * <p>Java class for FILER_INFO_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FILER_INFO_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="filer" type="{http://www.sec.gov/edgar/nmfp2}FILER_TYPE"/&gt;
 *         &lt;element name="liveTestFlag" type="{http://www.sec.gov/edgar/common}LIVE_TEST_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="contact" type="{http://www.sec.gov/edgar/nmfp2}CONTACT_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="notifications" type="{http://www.sec.gov/edgar/nmfp2}NOTIFICATIONS_TYPE" maxOccurs="30" minOccurs="0"/&gt;
 *         &lt;element name="confirmingCopyFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FILER_INFO_TYPE", propOrder = {
    "filer",
    "liveTestFlag",
    "contact",
    "notifications",
    "confirmingCopyFlag"
})
public class FILERINFOTYPE {

    @XmlElement(required = true)
    protected FILERTYPE filer;
    @XmlSchemaType(name = "token")
    protected LIVETESTTYPE liveTestFlag;
    protected CONTACTTYPE contact;
    protected List<NOTIFICATIONSTYPE> notifications;
    @XmlSchemaType(name = "token")
    protected YESNOTYPE confirmingCopyFlag;

    /**
     * Gets the value of the filer property.
     * 
     * @return
     *     possible object is
     *     {@link FILERTYPE }
     *     
     */
    public FILERTYPE getFiler() {
        return filer;
    }

    /**
     * Sets the value of the filer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FILERTYPE }
     *     
     */
    public void setFiler(FILERTYPE value) {
        this.filer = value;
    }

    /**
     * Gets the value of the liveTestFlag property.
     * 
     * @return
     *     possible object is
     *     {@link LIVETESTTYPE }
     *     
     */
    public LIVETESTTYPE getLiveTestFlag() {
        return liveTestFlag;
    }

    /**
     * Sets the value of the liveTestFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link LIVETESTTYPE }
     *     
     */
    public void setLiveTestFlag(LIVETESTTYPE value) {
        this.liveTestFlag = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link CONTACTTYPE }
     *     
     */
    public CONTACTTYPE getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTACTTYPE }
     *     
     */
    public void setContact(CONTACTTYPE value) {
        this.contact = value;
    }

    /**
     * Gets the value of the notifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOTIFICATIONSTYPE }
     * 
     * 
     */
    public List<NOTIFICATIONSTYPE> getNotifications() {
        if (notifications == null) {
            notifications = new ArrayList<NOTIFICATIONSTYPE>();
        }
        return this.notifications;
    }

    /**
     * Gets the value of the confirmingCopyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getConfirmingCopyFlag() {
        return confirmingCopyFlag;
    }

    /**
     * Sets the value of the confirmingCopyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setConfirmingCopyFlag(YESNOTYPE value) {
        this.confirmingCopyFlag = value;
    }

}
