//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * These elements are part of the FORM_DATA_TYPE group
 * 
 * <p>Java class for FORM_DATA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FORM_DATA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="generalInfo" type="{http://www.sec.gov/edgar/nmfp2}GENERAL_INFO_TYPE"/&gt;
 *         &lt;element name="seriesLevelInfo" type="{http://www.sec.gov/edgar/nmfp2}SERIES_LEVEL_INFO_TYPE"/&gt;
 *         &lt;element name="classLevelInfo" type="{http://www.sec.gov/edgar/nmfp2}CLASS_LEVEL_INFO_TYPE" maxOccurs="50"/&gt;
 *         &lt;element name="scheduleOfPortfolioSecuritiesInfo" type="{http://www.sec.gov/edgar/nmfp2}SCHEDULE_OF_PORTFOLIO_SECURITIES_INFO_TYPE" maxOccurs="9999"/&gt;
 *         &lt;element name="signature" type="{http://www.sec.gov/edgar/nmfp2}SIGNATURE_TYPE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FORM_DATA", propOrder = {
    "generalInfo",
    "seriesLevelInfo",
    "classLevelInfo",
    "scheduleOfPortfolioSecuritiesInfo",
    "signature"
})
public class FORMDATA {

    @XmlElement(required = true)
    protected GENERALINFOTYPE generalInfo;
    @XmlElement(required = true)
    protected SERIESLEVELINFOTYPE seriesLevelInfo;
    @XmlElement(required = true)
    protected List<CLASSLEVELINFOTYPE> classLevelInfo;
    @XmlElement(required = true)
    protected List<SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE> scheduleOfPortfolioSecuritiesInfo;
    @XmlElement(required = true)
    protected SIGNATURETYPE signature;

    /**
     * Gets the value of the generalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GENERALINFOTYPE }
     *     
     */
    public GENERALINFOTYPE getGeneralInfo() {
        return generalInfo;
    }

    /**
     * Sets the value of the generalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GENERALINFOTYPE }
     *     
     */
    public void setGeneralInfo(GENERALINFOTYPE value) {
        this.generalInfo = value;
    }

    /**
     * Gets the value of the seriesLevelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SERIESLEVELINFOTYPE }
     *     
     */
    public SERIESLEVELINFOTYPE getSeriesLevelInfo() {
        return seriesLevelInfo;
    }

    /**
     * Sets the value of the seriesLevelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SERIESLEVELINFOTYPE }
     *     
     */
    public void setSeriesLevelInfo(SERIESLEVELINFOTYPE value) {
        this.seriesLevelInfo = value;
    }

    /**
     * Gets the value of the classLevelInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classLevelInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassLevelInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLASSLEVELINFOTYPE }
     * 
     * 
     */
    public List<CLASSLEVELINFOTYPE> getClassLevelInfo() {
        if (classLevelInfo == null) {
            classLevelInfo = new ArrayList<CLASSLEVELINFOTYPE>();
        }
        return this.classLevelInfo;
    }

    /**
     * Gets the value of the scheduleOfPortfolioSecuritiesInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduleOfPortfolioSecuritiesInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduleOfPortfolioSecuritiesInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE }
     * 
     * 
     */
    public List<SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE> getScheduleOfPortfolioSecuritiesInfo() {
        if (scheduleOfPortfolioSecuritiesInfo == null) {
            scheduleOfPortfolioSecuritiesInfo = new ArrayList<SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE>();
        }
        return this.scheduleOfPortfolioSecuritiesInfo;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNATURETYPE }
     *     
     */
    public SIGNATURETYPE getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNATURETYPE }
     *     
     */
    public void setSignature(SIGNATURETYPE value) {
        this.signature = value;
    }

}
