//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import org.ici.nmfp2.edgar_common.YESNOTYPE;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * These elements are part of the GENERAL_INFO_TYPE group
 * 
 * <p>Java class for GENERAL_INFO_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GENERAL_INFO_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reportDate" type="{http://www.sec.gov/edgar/nmfp2common}DATE_TYPE"/&gt;
 *         &lt;element name="cik" type="{http://www.sec.gov/edgar/common}CIK_TYPE"/&gt;
 *         &lt;element name="registrantLEIId" type="{http://www.sec.gov/edgar/nmfp2common}STRING_20_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="seriesId" type="{http://www.sec.gov/edgar/nmfp2common}SERIES_ID_TYPE"/&gt;
 *         &lt;element name="totalShareClassesInSeries" type="{http://www.sec.gov/edgar/nmfp2common}INT_3_TYPE"/&gt;
 *         &lt;element name="finalFilingFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE"/&gt;
 *         &lt;element name="fundLiquidatingFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="fundMrgOrAcqrdByOthrFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="successorFund" type="{http://www.sec.gov/edgar/nmfp2}FUND_INFO_TYPE" maxOccurs="10" minOccurs="0"/&gt;
 *         &lt;element name="fundAcqrdOrMrgdWthAnthrFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE"/&gt;
 *         &lt;element name="acquiredMergedFund" type="{http://www.sec.gov/edgar/nmfp2}FUND_INFO_TYPE" maxOccurs="10" minOccurs="0"/&gt;
 *         &lt;element name="contact2" type="{http://www.sec.gov/edgar/nmfp2}CONTACT2_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GENERAL_INFO_TYPE", propOrder = {
    "reportDate",
    "cik",
    "registrantLEIId",
    "seriesId",
    "totalShareClassesInSeries",
    "finalFilingFlag",
    "fundLiquidatingFlag",
    "fundMrgOrAcqrdByOthrFlag",
    "successorFund",
    "fundAcqrdOrMrgdWthAnthrFlag",
    "acquiredMergedFund",
    "contact2"
})
public class GENERALINFOTYPE {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String cik;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String registrantLEIId;
    @XmlElement(required = true)
    protected String seriesId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalShareClassesInSeries;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected YESNOTYPE finalFilingFlag;
    @XmlSchemaType(name = "token")
    protected YESNOTYPE fundLiquidatingFlag;
    @XmlSchemaType(name = "token")
    protected YESNOTYPE fundMrgOrAcqrdByOthrFlag;
    protected List<FUNDINFOTYPE> successorFund;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected YESNOTYPE fundAcqrdOrMrgdWthAnthrFlag;
    protected List<FUNDINFOTYPE> acquiredMergedFund;
    protected CONTACT2TYPE contact2;

    /**
     * Gets the value of the reportDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportDate() {
        return reportDate;
    }

    /**
     * Sets the value of the reportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportDate(XMLGregorianCalendar value) {
        this.reportDate = value;
    }

    /**
     * Gets the value of the cik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCik() {
        return cik;
    }

    /**
     * Sets the value of the cik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCik(String value) {
        this.cik = value;
    }

    /**
     * Gets the value of the registrantLEIId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrantLEIId() {
        return registrantLEIId;
    }

    /**
     * Sets the value of the registrantLEIId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrantLEIId(String value) {
        this.registrantLEIId = value;
    }

    /**
     * Gets the value of the seriesId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesId() {
        return seriesId;
    }

    /**
     * Sets the value of the seriesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesId(String value) {
        this.seriesId = value;
    }

    /**
     * Gets the value of the totalShareClassesInSeries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalShareClassesInSeries() {
        return totalShareClassesInSeries;
    }

    /**
     * Sets the value of the totalShareClassesInSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalShareClassesInSeries(BigInteger value) {
        this.totalShareClassesInSeries = value;
    }

    /**
     * Gets the value of the finalFilingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getFinalFilingFlag() {
        return finalFilingFlag;
    }

    /**
     * Sets the value of the finalFilingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setFinalFilingFlag(YESNOTYPE value) {
        this.finalFilingFlag = value;
    }

    /**
     * Gets the value of the fundLiquidatingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getFundLiquidatingFlag() {
        return fundLiquidatingFlag;
    }

    /**
     * Sets the value of the fundLiquidatingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setFundLiquidatingFlag(YESNOTYPE value) {
        this.fundLiquidatingFlag = value;
    }

    /**
     * Gets the value of the fundMrgOrAcqrdByOthrFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getFundMrgOrAcqrdByOthrFlag() {
        return fundMrgOrAcqrdByOthrFlag;
    }

    /**
     * Sets the value of the fundMrgOrAcqrdByOthrFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setFundMrgOrAcqrdByOthrFlag(YESNOTYPE value) {
        this.fundMrgOrAcqrdByOthrFlag = value;
    }

    /**
     * Gets the value of the successorFund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the successorFund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuccessorFund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FUNDINFOTYPE }
     * 
     * 
     */
    public List<FUNDINFOTYPE> getSuccessorFund() {
        if (successorFund == null) {
            successorFund = new ArrayList<FUNDINFOTYPE>();
        }
        return this.successorFund;
    }

    /**
     * Gets the value of the fundAcqrdOrMrgdWthAnthrFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getFundAcqrdOrMrgdWthAnthrFlag() {
        return fundAcqrdOrMrgdWthAnthrFlag;
    }

    /**
     * Sets the value of the fundAcqrdOrMrgdWthAnthrFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setFundAcqrdOrMrgdWthAnthrFlag(YESNOTYPE value) {
        this.fundAcqrdOrMrgdWthAnthrFlag = value;
    }

    /**
     * Gets the value of the acquiredMergedFund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acquiredMergedFund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcquiredMergedFund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FUNDINFOTYPE }
     * 
     * 
     */
    public List<FUNDINFOTYPE> getAcquiredMergedFund() {
        if (acquiredMergedFund == null) {
            acquiredMergedFund = new ArrayList<FUNDINFOTYPE>();
        }
        return this.acquiredMergedFund;
    }

    /**
     * Gets the value of the contact2 property.
     * 
     * @return
     *     possible object is
     *     {@link CONTACT2TYPE }
     *     
     */
    public CONTACT2TYPE getContact2() {
        return contact2;
    }

    /**
     * Sets the value of the contact2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTACT2TYPE }
     *     
     */
    public void setContact2(CONTACT2TYPE value) {
        this.contact2 = value;
    }

}
