//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MARKET_FUND_CATEGORY_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MARKET_FUND_CATEGORY_TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Treasury"/&gt;
 *     &lt;enumeration value="Government/Agency"/&gt;
 *     &lt;enumeration value="Exempt Government"/&gt;
 *     &lt;enumeration value="Prime"/&gt;
 *     &lt;enumeration value="Single State"/&gt;
 *     &lt;enumeration value="Other Tax Exempt"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MARKET_FUND_CATEGORY_TYPE")
@XmlEnum
public enum MARKETFUNDCATEGORYTYPE {

    @XmlEnumValue("Treasury")
    TREASURY(1, "Treasury"),
    @XmlEnumValue("Government/Agency")
    GOVERNMENT_AGENCY(2, "Government/Agency"),
    @XmlEnumValue("Exempt Government")
    EXEMPT_GOVERNMENT(3, "Exempt Government"),
    @XmlEnumValue("Prime")
    PRIME(4, "Prime"),
    @XmlEnumValue("Single State")
    SINGLE_STATE(5, "Single State"),
    @XmlEnumValue("Other Tax Exempt")
    OTHER_TAX_EXEMPT(6, "Other Tax Exempt");

    private final int id;
    private final String value;

    MARKETFUNDCATEGORYTYPE(int id, String v) {
        this.id = id;
        value = v;
    }

    public int getId() {
        return id;
    }


    public String value() {
        return value;
    }

    public static MARKETFUNDCATEGORYTYPE fromValue(String v) {
        for (MARKETFUNDCATEGORYTYPE c: MARKETFUNDCATEGORYTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
