//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * These elements are part of the NET_SHAREHOLDER_FLOW_TYPE group
 * 
 * <p>Java class for NET_SHAREHOLDER_FLOW_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NET_SHAREHOLDER_FLOW_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="weeklyGrossSubscriptions" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="weeklyGrossRedemptions" type="{http://www.sec.gov/edgar/nmfp2common}DECIMAL_14_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NET_SHAREHOLDER_FLOW_TYPE", propOrder = {
    "weeklyGrossSubscriptions",
    "weeklyGrossRedemptions"
})
public class NETSHAREHOLDERFLOWTYPE {

    protected BigDecimal weeklyGrossSubscriptions;
    protected BigDecimal weeklyGrossRedemptions;

    /**
     * Gets the value of the weeklyGrossSubscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeeklyGrossSubscriptions() {
        return weeklyGrossSubscriptions;
    }

    /**
     * Sets the value of the weeklyGrossSubscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeeklyGrossSubscriptions(BigDecimal value) {
        this.weeklyGrossSubscriptions = value;
    }

    /**
     * Gets the value of the weeklyGrossRedemptions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeeklyGrossRedemptions() {
        return weeklyGrossRedemptions;
    }

    /**
     * Sets the value of the weeklyGrossRedemptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeeklyGrossRedemptions(BigDecimal value) {
        this.weeklyGrossRedemptions = value;
    }

}
