//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ici.nmfp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ici.nmfp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EdgarSubmission }
     * 
     */
    public EdgarSubmission createEdgarSubmission() {
        return new EdgarSubmission();
    }

    /**
     * Create an instance of {@link HEADERDATA }
     * 
     */
    public HEADERDATA createHEADERDATA() {
        return new HEADERDATA();
    }

    /**
     * Create an instance of {@link FORMDATA }
     * 
     */
    public FORMDATA createFORMDATA() {
        return new FORMDATA();
    }

    /**
     * Create an instance of {@link INVESTMENTMATURITYDATETYPE }
     * 
     */
    public INVESTMENTMATURITYDATETYPE createINVESTMENTMATURITYDATETYPE() {
        return new INVESTMENTMATURITYDATETYPE();
    }

    /**
     * Create an instance of {@link FILERCREDENTIALSTYPE }
     * 
     */
    public FILERCREDENTIALSTYPE createFILERCREDENTIALSTYPE() {
        return new FILERCREDENTIALSTYPE();
    }

    /**
     * Create an instance of {@link FILERTYPE }
     * 
     */
    public FILERTYPE createFILERTYPE() {
        return new FILERTYPE();
    }

    /**
     * Create an instance of {@link CONTACTTYPE }
     * 
     */
    public CONTACTTYPE createCONTACTTYPE() {
        return new CONTACTTYPE();
    }

    /**
     * Create an instance of {@link NOTIFICATIONSTYPE }
     * 
     */
    public NOTIFICATIONSTYPE createNOTIFICATIONSTYPE() {
        return new NOTIFICATIONSTYPE();
    }

    /**
     * Create an instance of {@link CONTACT2TYPE }
     * 
     */
    public CONTACT2TYPE createCONTACT2TYPE() {
        return new CONTACT2TYPE();
    }

    /**
     * Create an instance of {@link INDPPUBACCOUNTANTTYPE }
     * 
     */
    public INDPPUBACCOUNTANTTYPE createINDPPUBACCOUNTANTTYPE() {
        return new INDPPUBACCOUNTANTTYPE();
    }

    /**
     * Create an instance of {@link ADMINISTRATORTYPE }
     * 
     */
    public ADMINISTRATORTYPE createADMINISTRATORTYPE() {
        return new ADMINISTRATORTYPE();
    }

    /**
     * Create an instance of {@link TRANSFERAGENTTYPE }
     * 
     */
    public TRANSFERAGENTTYPE createTRANSFERAGENTTYPE() {
        return new TRANSFERAGENTTYPE();
    }

    /**
     * Create an instance of {@link COLLATERALISSUERSTYPE }
     * 
     */
    public COLLATERALISSUERSTYPE createCOLLATERALISSUERSTYPE() {
        return new COLLATERALISSUERSTYPE();
    }

    /**
     * Create an instance of {@link REPURCHASEAGREEMENTSTYPE }
     * 
     */
    public REPURCHASEAGREEMENTSTYPE createREPURCHASEAGREEMENTSTYPE() {
        return new REPURCHASEAGREEMENTSTYPE();
    }

    /**
     * Create an instance of {@link NRSROTYPE }
     * 
     */
    public NRSROTYPE createNRSROTYPE() {
        return new NRSROTYPE();
    }

    /**
     * Create an instance of {@link DEMANDFEATURETYPE }
     * 
     */
    public DEMANDFEATURETYPE createDEMANDFEATURETYPE() {
        return new DEMANDFEATURETYPE();
    }

    /**
     * Create an instance of {@link GUARANTORTYPE }
     * 
     */
    public GUARANTORTYPE createGUARANTORTYPE() {
        return new GUARANTORTYPE();
    }

    /**
     * Create an instance of {@link ENHANCEMENTPROVIDERTYPE }
     * 
     */
    public ENHANCEMENTPROVIDERTYPE createENHANCEMENTPROVIDERTYPE() {
        return new ENHANCEMENTPROVIDERTYPE();
    }

    /**
     * Create an instance of {@link FEEDERFUNDINFOTYPE }
     * 
     */
    public FEEDERFUNDINFOTYPE createFEEDERFUNDINFOTYPE() {
        return new FEEDERFUNDINFOTYPE();
    }

    /**
     * Create an instance of {@link FUNDINFOTYPE }
     * 
     */
    public FUNDINFOTYPE createFUNDINFOTYPE() {
        return new FUNDINFOTYPE();
    }

    /**
     * Create an instance of {@link ADVISERTYPE }
     * 
     */
    public ADVISERTYPE createADVISERTYPE() {
        return new ADVISERTYPE();
    }

    /**
     * Create an instance of {@link NETSHAREHOLDERFLOWTYPE }
     * 
     */
    public NETSHAREHOLDERFLOWTYPE createNETSHAREHOLDERFLOWTYPE() {
        return new NETSHAREHOLDERFLOWTYPE();
    }

    /**
     * Create an instance of {@link FILERINFOTYPE }
     * 
     */
    public FILERINFOTYPE createFILERINFOTYPE() {
        return new FILERINFOTYPE();
    }

    /**
     * Create an instance of {@link GENERALINFOTYPE }
     * 
     */
    public GENERALINFOTYPE createGENERALINFOTYPE() {
        return new GENERALINFOTYPE();
    }

    /**
     * Create an instance of {@link SERIESLEVELINFOTYPE }
     * 
     */
    public SERIESLEVELINFOTYPE createSERIESLEVELINFOTYPE() {
        return new SERIESLEVELINFOTYPE();
    }

    /**
     * Create an instance of {@link CLASSLEVELINFOTYPE }
     * 
     */
    public CLASSLEVELINFOTYPE createCLASSLEVELINFOTYPE() {
        return new CLASSLEVELINFOTYPE();
    }

    /**
     * Create an instance of {@link SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE }
     * 
     */
    public SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE createSCHEDULEOFPORTFOLIOSECURITIESINFOTYPE() {
        return new SCHEDULEOFPORTFOLIOSECURITIESINFOTYPE();
    }

    /**
     * Create an instance of {@link SIGNATURETYPE }
     * 
     */
    public SIGNATURETYPE createSIGNATURETYPE() {
        return new SIGNATURETYPE();
    }

}
