//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EXACT_OR_EXPLANATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXACT_OR_EXPLANATION"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="date" type="{http://www.sec.gov/edgar/common}DATE_TYPE"/&gt;
 *         &lt;element name="exactOrExplanation" type="{http://www.sec.gov/edgar/common}EXACT_OR_EXPLANATION_OPTIONS"/&gt;
 *         &lt;element name="explanationInfo" type="{http://www.sec.gov/edgar/common}STRING_1K_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXACT_OR_EXPLANATION", propOrder = {
    "date",
    "exactOrExplanation",
    "explanationInfo"
})
public class EXACTOREXPLANATION {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String date;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected EXACTOREXPLANATIONOPTIONS exactOrExplanation;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String explanationInfo;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the exactOrExplanation property.
     * 
     * @return
     *     possible object is
     *     {@link EXACTOREXPLANATIONOPTIONS }
     *     
     */
    public EXACTOREXPLANATIONOPTIONS getExactOrExplanation() {
        return exactOrExplanation;
    }

    /**
     * Sets the value of the exactOrExplanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXACTOREXPLANATIONOPTIONS }
     *     
     */
    public void setExactOrExplanation(EXACTOREXPLANATIONOPTIONS value) {
        this.exactOrExplanation = value;
    }

    /**
     * Gets the value of the explanationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanationInfo() {
        return explanationInfo;
    }

    /**
     * Sets the value of the explanationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanationInfo(String value) {
        this.explanationInfo = value;
    }

}
