//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FLAG_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FLAG_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="confirmingCopyFlag" type="{http://www.sec.gov/edgar/common}TRUE_FALSE_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="delayingAmendmentFlag" type="{http://www.sec.gov/edgar/common}TRUE_FALSE_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="overrideInternetFlag" type="{http://www.sec.gov/edgar/common}TRUE_FALSE_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="returnCopyFlag" type="{http://www.sec.gov/edgar/common}TRUE_FALSE_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="serialFlag" type="{http://www.sec.gov/edgar/common}TRUE_FALSE_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FLAG_TYPE", propOrder = {
    "confirmingCopyFlag",
    "delayingAmendmentFlag",
    "overrideInternetFlag",
    "returnCopyFlag",
    "serialFlag"
})
public class FLAGTYPE {

    protected Boolean confirmingCopyFlag;
    protected Boolean delayingAmendmentFlag;
    protected Boolean overrideInternetFlag;
    protected Boolean returnCopyFlag;
    protected Boolean serialFlag;

    /**
     * Gets the value of the confirmingCopyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConfirmingCopyFlag() {
        return confirmingCopyFlag;
    }

    /**
     * Sets the value of the confirmingCopyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConfirmingCopyFlag(Boolean value) {
        this.confirmingCopyFlag = value;
    }

    /**
     * Gets the value of the delayingAmendmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelayingAmendmentFlag() {
        return delayingAmendmentFlag;
    }

    /**
     * Sets the value of the delayingAmendmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelayingAmendmentFlag(Boolean value) {
        this.delayingAmendmentFlag = value;
    }

    /**
     * Gets the value of the overrideInternetFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverrideInternetFlag() {
        return overrideInternetFlag;
    }

    /**
     * Sets the value of the overrideInternetFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverrideInternetFlag(Boolean value) {
        this.overrideInternetFlag = value;
    }

    /**
     * Gets the value of the returnCopyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnCopyFlag() {
        return returnCopyFlag;
    }

    /**
     * Sets the value of the returnCopyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnCopyFlag(Boolean value) {
        this.returnCopyFlag = value;
    }

    /**
     * Gets the value of the serialFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSerialFlag() {
        return serialFlag;
    }

    /**
     * Sets the value of the serialFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSerialFlag(Boolean value) {
        this.serialFlag = value;
    }

}
