//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 *  Single module segment type
 * 
 * <p>Java class for MODULE_SEGMENT_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MODULE_SEGMENT_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="modOrSegFlag" type="{http://www.sec.gov/edgar/common}MODULE_OR_SEGMENT_FLAG"/&gt;
 *         &lt;element name="nickName" type="{http://www.sec.gov/edgar/common}MODULE_SEGMENT_NAME_TYPE"/&gt;
 *         &lt;element name="cik" type="{http://www.sec.gov/edgar/common}CIK_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="ccc" type="{http://www.sec.gov/edgar/common}CCC_TYPE" minOccurs="0"/&gt;
 *         &lt;element name="documentType" type="{http://www.sec.gov/edgar/common}MODULE_SEGMENT_FORM_TYPE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MODULE_SEGMENT_TYPE", propOrder = {
    "modOrSegFlag",
    "nickName",
    "cik",
    "ccc",
    "documentType"
})
public class MODULESEGMENTTYPE {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected MODULEORSEGMENTFLAG modOrSegFlag;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nickName;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String cik;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ccc;
    @XmlList
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected List<String> documentType;

    /**
     * Gets the value of the modOrSegFlag property.
     * 
     * @return
     *     possible object is
     *     {@link MODULEORSEGMENTFLAG }
     *     
     */
    public MODULEORSEGMENTFLAG getModOrSegFlag() {
        return modOrSegFlag;
    }

    /**
     * Sets the value of the modOrSegFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link MODULEORSEGMENTFLAG }
     *     
     */
    public void setModOrSegFlag(MODULEORSEGMENTFLAG value) {
        this.modOrSegFlag = value;
    }

    /**
     * Gets the value of the nickName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * Sets the value of the nickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNickName(String value) {
        this.nickName = value;
    }

    /**
     * Gets the value of the cik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCik() {
        return cik;
    }

    /**
     * Sets the value of the cik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCik(String value) {
        this.cik = value;
    }

    /**
     * Gets the value of the ccc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcc() {
        return ccc;
    }

    /**
     * Sets the value of the ccc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcc(String value) {
        this.ccc = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDocumentType() {
        if (documentType == null) {
            documentType = new ArrayList<String>();
        }
        return this.documentType;
    }

}
