//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ici.nmfp.edgar_common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ici.nmfp.edgar_common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DEPOSITORTYPE }
     * 
     */
    public DEPOSITORTYPE createDEPOSITORTYPE() {
        return new DEPOSITORTYPE();
    }

    /**
     * Create an instance of {@link SUCCESSORTYPE }
     * 
     */
    public SUCCESSORTYPE createSUCCESSORTYPE() {
        return new SUCCESSORTYPE();
    }

    /**
     * Create an instance of {@link CONTACTTYPE }
     * 
     */
    public CONTACTTYPE createCONTACTTYPE() {
        return new CONTACTTYPE();
    }

    /**
     * Create an instance of {@link FLAGTYPE }
     * 
     */
    public FLAGTYPE createFLAGTYPE() {
        return new FLAGTYPE();
    }

    /**
     * Create an instance of {@link NOTIFICATIONTYPE }
     * 
     */
    public NOTIFICATIONTYPE createNOTIFICATIONTYPE() {
        return new NOTIFICATIONTYPE();
    }

    /**
     * Create an instance of {@link SROSTYPE }
     * 
     */
    public SROSTYPE createSROSTYPE() {
        return new SROSTYPE();
    }

    /**
     * Create an instance of {@link INVESTMENTCOMPANYTYPE }
     * 
     */
    public INVESTMENTCOMPANYTYPE createINVESTMENTCOMPANYTYPE() {
        return new INVESTMENTCOMPANYTYPE();
    }

    /**
     * Create an instance of {@link MODULESEGMENTTYPE }
     * 
     */
    public MODULESEGMENTTYPE createMODULESEGMENTTYPE() {
        return new MODULESEGMENTTYPE();
    }

    /**
     * Create an instance of {@link MODULESSEGMENTTYPE }
     * 
     */
    public MODULESSEGMENTTYPE createMODULESSEGMENTTYPE() {
        return new MODULESSEGMENTTYPE();
    }

    /**
     * Create an instance of {@link EDGARDOCUMENTTYPE }
     * 
     */
    public EDGARDOCUMENTTYPE createEDGARDOCUMENTTYPE() {
        return new EDGARDOCUMENTTYPE();
    }

    /**
     * Create an instance of {@link EDGARDOCUMENTSTYPE }
     * 
     */
    public EDGARDOCUMENTSTYPE createEDGARDOCUMENTSTYPE() {
        return new EDGARDOCUMENTSTYPE();
    }

    /**
     * Create an instance of {@link CONFIDENTIALDOCUMENTTYPE }
     * 
     */
    public CONFIDENTIALDOCUMENTTYPE createCONFIDENTIALDOCUMENTTYPE() {
        return new CONFIDENTIALDOCUMENTTYPE();
    }

    /**
     * Create an instance of {@link CONFIDENTIALDOCUMENTSTYPE }
     * 
     */
    public CONFIDENTIALDOCUMENTSTYPE createCONFIDENTIALDOCUMENTSTYPE() {
        return new CONFIDENTIALDOCUMENTSTYPE();
    }

    /**
     * Create an instance of {@link CONFIDENTIALDOCUMENTTYPE1 }
     * 
     */
    public CONFIDENTIALDOCUMENTTYPE1 createCONFIDENTIALDOCUMENTTYPE1() {
        return new CONFIDENTIALDOCUMENTTYPE1();
    }

    /**
     * Create an instance of {@link CONFIDENTIALDOCUMENTSTYPE1 }
     * 
     */
    public CONFIDENTIALDOCUMENTSTYPE1 createCONFIDENTIALDOCUMENTSTYPE1() {
        return new CONFIDENTIALDOCUMENTSTYPE1();
    }

    /**
     * Create an instance of {@link FISCALYEARTYPE }
     * 
     */
    public FISCALYEARTYPE createFISCALYEARTYPE() {
        return new FISCALYEARTYPE();
    }

    /**
     * Create an instance of {@link ADDRESSTYPE }
     * 
     */
    public ADDRESSTYPE createADDRESSTYPE() {
        return new ADDRESSTYPE();
    }

    /**
     * Create an instance of {@link FILERTYPE }
     * 
     */
    public FILERTYPE createFILERTYPE() {
        return new FILERTYPE();
    }

    /**
     * Create an instance of {@link OTHERTYPE }
     * 
     */
    public OTHERTYPE createOTHERTYPE() {
        return new OTHERTYPE();
    }

    /**
     * Create an instance of {@link OTHERTYPE2 }
     * 
     */
    public OTHERTYPE2 createOTHERTYPE2() {
        return new OTHERTYPE2();
    }

    /**
     * Create an instance of {@link STATECOUNTRYTYPE }
     * 
     */
    public STATECOUNTRYTYPE createSTATECOUNTRYTYPE() {
        return new STATECOUNTRYTYPE();
    }

    /**
     * Create an instance of {@link SIGNATURETYPE }
     * 
     */
    public SIGNATURETYPE createSIGNATURETYPE() {
        return new SIGNATURETYPE();
    }

    /**
     * Create an instance of {@link NAMETYPE2 }
     * 
     */
    public NAMETYPE2 createNAMETYPE2() {
        return new NAMETYPE2();
    }

    /**
     * Create an instance of {@link SIGNATURETYPE2 }
     * 
     */
    public SIGNATURETYPE2 createSIGNATURETYPE2() {
        return new SIGNATURETYPE2();
    }

    /**
     * Create an instance of {@link SIGNATURETYPE3 }
     * 
     */
    public SIGNATURETYPE3 createSIGNATURETYPE3() {
        return new SIGNATURETYPE3();
    }

    /**
     * Create an instance of {@link FILERCREDENTIALS }
     * 
     */
    public FILERCREDENTIALS createFILERCREDENTIALS() {
        return new FILERCREDENTIALS();
    }

    /**
     * Create an instance of {@link EDGARLITEADDRESSTYPE }
     * 
     */
    public EDGARLITEADDRESSTYPE createEDGARLITEADDRESSTYPE() {
        return new EDGARLITEADDRESSTYPE();
    }

    /**
     * Create an instance of {@link CONTACTEMAILTYPE }
     * 
     */
    public CONTACTEMAILTYPE createCONTACTEMAILTYPE() {
        return new CONTACTEMAILTYPE();
    }

    /**
     * Create an instance of {@link SIGNATURETYPE4 }
     * 
     */
    public SIGNATURETYPE4 createSIGNATURETYPE4() {
        return new SIGNATURETYPE4();
    }

    /**
     * Create an instance of {@link ABSASSETCLASSTYPES }
     * 
     */
    public ABSASSETCLASSTYPES createABSASSETCLASSTYPES() {
        return new ABSASSETCLASSTYPES();
    }

    /**
     * Create an instance of {@link ABSSUBASSETCLASSTYPES }
     * 
     */
    public ABSSUBASSETCLASSTYPES createABSSUBASSETCLASSTYPES() {
        return new ABSSUBASSETCLASSTYPES();
    }

    /**
     * Create an instance of {@link IRSORSSN }
     * 
     */
    public IRSORSSN createIRSORSSN() {
        return new IRSORSSN();
    }

    /**
     * Create an instance of {@link INDIVIDUALNAMETYPE }
     * 
     */
    public INDIVIDUALNAMETYPE createINDIVIDUALNAMETYPE() {
        return new INDIVIDUALNAMETYPE();
    }

    /**
     * Create an instance of {@link EXACTOREXPLANATION }
     * 
     */
    public EXACTOREXPLANATION createEXACTOREXPLANATION() {
        return new EXACTOREXPLANATION();
    }

}
