//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sec.gov/edgar/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ici.nmfp2.edgar_common;
