//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RPT_OWNER_RELATIONSHIP_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RPT_OWNER_RELATIONSHIP_TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="DIRECTOR"/&gt;
 *     &lt;enumeration value="OFFICER"/&gt;
 *     &lt;enumeration value="OWNER"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RPT_OWNER_RELATIONSHIP_TYPE")
@XmlEnum
public enum RPTOWNERRELATIONSHIPTYPE {

    DIRECTOR,
    OFFICER,
    OWNER,
    OTHER;

    public String value() {
        return name();
    }

    public static org.ici.nmfp2.edgar_common.RPTOWNERRELATIONSHIPTYPE fromValue(String v) {
        return valueOf(v);
    }

}
