//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SRO_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SRO_TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="AMEX"/&gt;
 *     &lt;enumeration value="ARCA"/&gt;
 *     &lt;enumeration value="BSE"/&gt;
 *     &lt;enumeration value="CBOE"/&gt;
 *     &lt;enumeration value="CHX"/&gt;
 *     &lt;enumeration value="FINRA"/&gt;
 *     &lt;enumeration value="ISE"/&gt;
 *     &lt;enumeration value="NASD"/&gt;
 *     &lt;enumeration value="NSX"/&gt;
 *     &lt;enumeration value="NYSE"/&gt;
 *     &lt;enumeration value="PCX"/&gt;
 *     &lt;enumeration value="PHLX"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SRO_TYPE")
@XmlEnum
public enum SROTYPE {

    NONE,
    AMEX,
    ARCA,
    BSE,
    CBOE,
    CHX,
    FINRA,
    ISE,
    NASD,
    NSX,
    NYSE,
    PCX,
    PHLX;

    public String value() {
        return name();
    }

    public static SROTYPE fromValue(String v) {
        return valueOf(v);
    }

}
