//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:42:33 AM EDT 
//


package org.ici.nmfp2.edgar_common;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SUCCESSOR_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SUCCESSOR_TYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="successorFilingFlag" type="{http://www.sec.gov/edgar/common}YES_NO_TYPE"/&gt;
 *         &lt;element name="successorFileNumber" type="{http://www.sec.gov/edgar/common}FILE_NUMBER_TYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SUCCESSOR_TYPE", propOrder = {
    "successorFilingFlag",
    "successorFileNumber"
})
public class SUCCESSORTYPE {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected YESNOTYPE successorFilingFlag;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String successorFileNumber;

    /**
     * Gets the value of the successorFilingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOTYPE }
     *     
     */
    public YESNOTYPE getSuccessorFilingFlag() {
        return successorFilingFlag;
    }

    /**
     * Sets the value of the successorFilingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOTYPE }
     *     
     */
    public void setSuccessorFilingFlag(YESNOTYPE value) {
        this.successorFilingFlag = value;
    }

    /**
     * Gets the value of the successorFileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccessorFileNumber() {
        return successorFileNumber;
    }

    /**
     * Sets the value of the successorFileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccessorFileNumber(String value) {
        this.successorFileNumber = value;
    }

}
